# Generated by Django 6.0 on 2025-12-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_interests', models.JSONField(blank=True, default=list)),
                ('has_career_in_mind', models.BooleanField(default=False)),
                ('target_career', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_level', models.IntegerField(default=0, help_text='1-5 scale')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
