# Generated by Django 6.0 on 2025-12-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='primary_trait',
            field=models.CharField(blank=True, choices=[('ANALYTICAL', 'Analytical Thinking'), ('CREATIVE', 'Creative Expression'), ('SOCIAL', 'Social Engagement'), ('TECHNICAL', 'Technical Aptitude'), ('STRUCTURED', 'Structured Execution')], help_text='The primary personality trait this career appeals to', max_length=20, null=True),
        ),
    ]
