@echo off
echo Starting SkillMatch Hub Development Environment...

echo Starting Tailwind CSS Watcher...
start "Tailwind Watcher" cmd /k "venv\Scripts\activate && python manage.py tailwind start"

echo Starting Django Server...
cmd /k "venv\Scripts\activate && python manage.py runserver"
