@echo off
echo Starting SkillMatch Hub Server...
echo Activating Virtual Environment...
call venv\Scripts\activate
echo Virtual Environment Activated.
echo Starting Django Server...
python manage.py runserver
pause
