# Generated by Django 6.0 on 2025-12-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('INTEREST', 'Interest'), ('SKILL', 'Skill Perception'), ('SCENARIO', 'Scenario')], default='INTEREST', max_length=20)),
                ('primary_trait', models.CharField(blank=True, choices=[('ANALYTICAL', 'Analytical Thinking'), ('CREATIVE', 'Creative Expression'), ('SOCIAL', 'Social Engagement'), ('TECHNICAL', 'Technical Aptitude'), ('STRUCTURED', 'Structured Execution')], max_length=20, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('trait_associated', models.CharField(choices=[('ANALYTICAL', 'Analytical Thinking'), ('CREATIVE', 'Creative Expression'), ('SOCIAL', 'Social Engagement'), ('TECHNICAL', 'Technical Aptitude'), ('STRUCTURED', 'Structured Execution')], max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_score', models.IntegerField(blank=True, help_text='1-5 score', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.answeroption')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
